databases:
  - name: instagram_DB
    databaseName: instagram_db_m7ak
    user: instagram
    region: singapore

services:
  - type: web
    name: instagram
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: instagram_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

